<a href="https://colab.research.google.com/github/chominyeong/PyTorch-DeepLearning-Start/blob/main/Ch02_%ED%8C%8C%EC%9D%B4%ED%86%A0%EC%B9%98_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
# 파이썬으로 설명하면 List를 생성해서 np.array로 1차원 array로 변환함.
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [ ]:
print('Rank of t: ', t.ndim)   #차원
print('Shape of t: ', t.shape) #크기  (7,)는 (1,7)을 의미, (1x7) 크기의 벡터

Rank of t:  1
Shape of t:  (7,)


In [ ]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])

t[0] t[1] t[-1] =  0.0 1.0 6.0


In [ ]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [ ]:
print('Rank  of t: ', t.ndim)  #차원
print('Shape of t: ', t.shape) #크기

Rank  of t:  2
Shape of t:  (4, 3)


In [ ]:
import torch

In [ ]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [ ]:
t.dim()  #차원

1

In [ ]:
t.shape  #크기

torch.Size([7])

In [ ]:
t.size() #크기

torch.Size([7])

In [ ]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
t.dim()  # rank. 즉, 차원

2

In [ ]:
t.size() # shape

torch.Size([4, 3])

슬라이싱

In [ ]:
print(t[:, 1])  #모든 행, 두번째 열 ↔ 첫번째 차원에서 두번째 차원의 1번 인덱스만 가져온다.

tensor([ 2.,  5.,  8., 11.])


In [ ]:
print(t[:, 1].size())

torch.Size([4])


In [ ]:
print(t[:, :-1]) #모든 행, 마지막 열 제외

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


같은 크기

In [ ]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])

In [ ]:
a = m1 + m2
a

tensor([[5., 5.]])

In [ ]:
a.shape

torch.Size([1, 2])

In [ ]:
a.size()

torch.Size([1, 2])

In [ ]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]]) #크기 : (1,2)
m2 = torch.FloatTensor([3])      #크기 : (1,)   #크기변경 [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


matmul vs. mul

In [ ]:
# matmul (행렬 곱셈)
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1

print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [ ]:
# element-wise 곱셈
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1

print(m1 * m2) # 2 x 2
print(m1.mul(m2))
# 두 행렬의 크기는 다르다. element-wise 곱셈을 수행하면,
# 브로드캐스팅이 된 후에 곱셈이 수행된다.(m2의 크기가 변한 것)

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


평균

In [ ]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.mean())

tensor(2.5000)


In [ ]:
# 차원을 인자로 보는 경우
#dim=0 : 첫 번째 차원(행)
#인자로 dim을 준다면 해당 차원을 제거한다는 의미 → 열만 남기겠다.
#(2,2) → (1,2)
#1과 3의 평균을 구하고, 2와 4의 평균을 구한다.

t.mean(dim=0)

tensor([2., 3.])

In [ ]:
#dim=1 : 열
#해당 차원 제거 → 행만 남기겠다.
#(2,2) → (2,1)
#1과 2의 평균을 구하고, 3과 4의 평균을 구한다.

print(t.mean(dim=1))

tensor([1.5000, 3.5000])


In [ ]:
# ↑행만 남겼으므로 열의 차원이 제거되어야 한다. (2,2) → (2,1)
# 결국 1차원이므로 (1,2)와 같이 표현되므로 위와 같은 결과가 나온다.
#dim = -1 : 마지막 차원을 제거한다. 열의 차원을 제거한다.
#결과가 같게 나온다.
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


덧셈

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])  #(2,2)
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


최대

In [ ]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(t.max()) # Returns one value: max

tensor(4.)


In [ ]:
# dim=0
print(t.max(dim=0)) # Returns two values: max and argmax

#결과는 [3,4]이다.
#max에 dim인자를 주면 argmax도 함께 리터한다. [1,1]

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


차원

1차원

In [ ]:
#1차원 배열
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [ ]:
print(arr.shape)

(3,)


2차원 배열

In [ ]:
#2차원 배열
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr.shape)

(2, 3)


3차원 배열

In [ ]:
#3차원 배열
arr = np.array([[[1, 2, 3],
                 [4, 5, 6]],
                [[7, 8, 9],
                 [10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(arr.shape)

(2, 2, 3)


In [ ]:
np.sum(arr, axis=0)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
np.sum(arr, axis=1)

array([[ 5,  7,  9],
       [17, 19, 21]])

In [ ]:
np.sum(arr, axis=2)

array([[ 6, 15],
       [24, 33]])

In [ ]:
#3차원 배열
arr = np.array([[[1,4], [2,5], [3,6]],
                [[7,10],[8,11],[9,12]]])
print(arr)

[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]


In [ ]:
print(arr.shape)

(2, 3, 2)


In [ ]:
arr = np.array([[[1, 4, 7],[2, 9, 7],[1, 3, 0],[9, 6, 9]],
                [[2, 3, 4],[1, 3, 5],[4, 6, 2],[2, 0, 8]]])
print(arr)

[[[1 4 7]
  [2 9 7]
  [1 3 0]
  [9 6 9]]

 [[2 3 4]
  [1 3 5]
  [4 6 2]
  [2 0 8]]]


In [ ]:
print(arr.shape)

(2, 4, 3)


뷰

In [ ]:
t = [[[0, 1, 2],
      [3, 4, 5]],
     [[6, 7, 8],
      [9, 10, 11]]]
ft = torch.FloatTensor(t)

In [ ]:
ft.size()  # (차원, 행, 렬) 2x3 행렬이 2개 존재

torch.Size([2, 2, 3])

In [ ]:
# 3차원 텐서 → 2차원 텐서
print(ft.view([-1, 3])) # ft라는 텐서를 (4, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


(2,2,3) → (2x2, 3) → (4, 3)

In [ ]:
# 3차원 텐서의 크기 변경
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)  # (1x3) 행렬 4개로 변경

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


스퀴즈

In [ ]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)  # (3 x 1)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
print(ft.squeeze())  # (3,)
print(ft)

tensor([0., 1., 2.])
tensor([[0.],
        [1.],
        [2.]])


In [ ]:
print(ft.squeeze_())
print(ft)

tensor([0., 1., 2.])
tensor([0., 1., 2.])


언스퀴즈

In [ ]:
ft = torch.Tensor([0, 1, 2])  #(3,)
print(ft.shape)

torch.Size([3])


In [ ]:
# 인자를 0으로
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)  #(1, 3)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
# unsqueeze를 view로도 구현 가능
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [ ]:
# 인자를 1로
print(ft.unsqueeze(1))   #(3, 1)
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [ ]:
# 인자를 -1로
print(ft.unsqueeze(-1))   #(3, 1)
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


타입캐스팅

long → float 타입

In [ ]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [ ]:
# float형으로 타입 변경
print(lt.float())

tensor([1., 2., 3., 4.])


bt → long, float 타입

In [ ]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [ ]:
# long, float형으로 타입 변경
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


연결하기(concatenate)

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [ ]:
print(torch.cat([x,y]))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [ ]:
# dim=0 ; 첫번째 차원을 늘린다.
print(torch.cat([x, y], dim=0))  #(2x2) 2개 → (4x2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [ ]:
# dim=1 ; 두번째 차원을 늘린다.
print(torch.cat([x,y],dim=1))  #(2x2) 2개 → (2x4)

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


스택킹

In [ ]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])  #(2,)

In [ ]:
print(torch.cat([x, y, z]))    #(6,)

tensor([1., 4., 2., 5., 3., 6.])


In [ ]:
print(torch.stack([x, y, z]))  #(3, 2)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
# stack은 다음의 코드와 동일하다.
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
print(torch.stack([x, y, z], dim=1))  #(2, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


ones_like & zeros_like

In [ ]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [ ]:
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])


in-place

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [ ]:
x

tensor([[1., 2.],
        [3., 4.]])

In [ ]:
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [ ]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 새로운 값(덮어쓰기) 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


class

In [1]:
import torch

함수로 덧셈기 구현하기

In [3]:
# 전역변수 선언
result = 0

In [5]:
def add(num):
    global result
    result += num
    return result

In [6]:
print(add(3))
print(add(4))

3
7


함수로 두 개의 덧셈기 구현하기   
- 책상에 두 개의 계산기를 두고 서로 다른 연산

In [7]:
result1 = 0
result2 = 0

def add1(num):
    global result1
    result1 += num
    return result1

def add2(num):
    global result2
    result2 += num
    return result2

print(add1(3))
print(add1(4))
print(add2(3))
print(add2(7))

3
7
3
10


클래스로 덧셈기 구현하기
- 클래스 = 붕어빵 틀

In [8]:
class Calculator:
    def __init__(self): # 객체 생성 시 호출될 때 실행되는 "초기화" 함수. 이를 생성자라고 한다.
        self.result = 0

    def add(self, num): # 객체 생성 후 사용할 수 있는 함수.
        self.result += num
        return self.result

- 객체 = 붕어빵

In [9]:
# ca1이라는 객체 생성
cal1 = Calculator()

In [10]:
cal2 = Calculator()

두 개의 덧셈기를 함수로 구현하려면 함수를 두 개 만들어야 하지만, 클래스는 하나를 생성하고 이 클래스를 통해 별도의 객체를 여러 개 생성할 수 있다.

In [11]:
print(cal1.add(3))
print(cal1.add(4))
print(cal2.add(3))
print(cal2.add(7))

3
7
3
10
